# Generated by Django 5.0.1 on 2024-01-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrocApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gm_pk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
