# Generated by Django 5.0.1 on 2024-01-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrocApp', '0002_product_gm_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
